[blog_hentioe_dev]
title = "绅士喵"
url = "https://blog.hentioe.dev"
entrySelector = "main > div > div > a"
titleSelector = "div > h2"
# 根据 https://gitlab.com/vincenttunru/feed-me-up-scotty/-/blob/f7ae188f890fbb539a9d07b19279f1e5d2e6c6ca/src/parse.ts#L30
# 如果为 *，则代表本身
linkSelector = "*"

[daxiaamu]
title = "大侠阿木博客"
url = "https://www.daxiaamu.com"
entrySelector = "#postlist > div.post-item"
titleSelector = ".mdui-card-primary-title, div.mdui-card-actions > a > h1"
linkSelector = "div.mdui-card-media > a, div.mdui-card-actions > a.ainList"

[blog_z-labs_eu]
title = "Z - Labs Blog"
url = "https://blog.z-labs.eu/"
entrySelector = "ul.posts > li"
titleSelector = "a.post-link"
linkSelector = "a.post-link"

[kebingzao_com]
title = "Zach Ke's Notes"
url = "https://kebingzao.com/"
entrySelector = "article.post > div.post-block"
titleSelector = "a.post-title-link"
linkSelector = "a.post-title-link"

[www_debugwar_com]
title = "Debugwar - Step in or Step over, this is a problem ..."
url = "https://www.debugwar.com/"
entrySelector = "div.MuiPaper-root.MuiCard-root"
titleSelector = "h1 > a"
linkSelector = "h1 > a"

[mouri_moe]
title = "大贤者初春令月 Mouri_Naruto"
url = "https://mouri.moe/zh/"
entrySelector = "article"
titleSelector = "h1 > a"
linkSelector = "h1 > a"
